version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: sdmdev01
      POSTGRES_PASSWORD: tyKul25
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev-postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: sdmdev01
      SPRING_DATASOURCE_PASSWORD: tyKul25
    ports:
      - "8080:8080"

volumes:
  pgdata:
