# ===========================================================
# JPA / Hibernate
# ===========================================================
#
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=ALWAYS
spring.jpa.hibernate.ddl-auto=none

spring.artemis.mode=native
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=artemis
spring.artemis.password=simetraehcapa

logging.level.org.springframework.jms=DEBUG
logging.level.org.springframework.jms.listener=DEBUG
logging.level.org.springframework.boot.autoconfigure.jms=DEBUG

