# application.properties
spring.datasource.url=jdbc:postgresql://192.168.178.124:5432/sdm_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sdm_user
spring.datasource.password=0520912772
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
