# ---------------------------
# Server
# ---------------------------
server.port=8099
#server.use-forwarded-headers=true

# ---------------------------
# KeyCloak
# ---------------------------


#
# ---------------------------
# Spring Boot Actuator
# ---------------------------
# TODO ...

# ----------------------------------------------------
# SDM Database
# ----------------------------------------------------
spring.sql.init.mode=always
spring.datasource.username=sdmdev01
spring.datasource.password=tyKul25

#
# ---------------------------
# SpringDoc / Swagger
# ---------------------------
# TODO ...
#springdoc.api-docs.path=/api-docs/openapi
#springdoc.api-docs.enabled=true
#
#springdoc.swagger-ui.path=/api-docs/swagger-ui.html
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.operationsSorter=alpha
#springdoc.swagger-ui.tagsSorter=alpha
#springdoc.swagger-ui.displayRequestDuration=true
#
