--  Department Table
CREATE TABLE IF NOT EXISTS departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ
);

--  Users Table
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    username VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100),
    surname VARCHAR(100),
    enabled BOOLEAN,
    department_id INTEGER,
    FOREIGN KEY (department_id) REFERENCES departments(id)
);

--  Devices Table
CREATE TABLE IF NOT EXISTS devices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    name VARCHAR(100),
    type VARCHAR(50),
    status VARCHAR(50),
    serial_number VARCHAR(50) UNIQUE,
    manufacturer VARCHAR(100),
    location VARCHAR(100),
    purchase_date DATE,
    user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

--  Handover Protocol Table
CREATE TABLE IF NOT EXISTS handover_protocols (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL,
    receiver_user_id INTEGER NOT NULL,
    performed_by_user_id INTEGER NOT NULL,
    department_id INTEGER NOT NULL,
    description TEXT,
    is_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    action_type VARCHAR(50),
    handover_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_device FOREIGN KEY (device_id) REFERENCES devices(id),
    CONSTRAINT fk_receiver_user FOREIGN KEY (receiver_user_id) REFERENCES users(id),
    CONSTRAINT fk_performer_user FOREIGN KEY (performed_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES departments(id)
);
