-- 🔧 Department Table
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255), -- todo unique
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- 🔧 Users Table
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    username VARCHAR(255) NOT NULL UNIQUE, --TODO define contraint for min
    name VARCHAR(255),
    -- TODO add familyname
    password VARCHAR(255), -- TODO remove this
    enabled BOOLEAN,
    department_id BIGINT,
    FOREIGN KEY (department_id) REFERENCES departments(id)
);

-- 🔧 Devices Table
CREATE TABLE devices (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    name VARCHAR(255),
    type VARCHAR(255),
    status VARCHAR(50), -- assumes enum is stored as String
    serial_number VARCHAR(255) UNIQUE,
    manufacturer VARCHAR(255),
    location VARCHAR(255),
    purchase_date DATE,
    user_id BIGINT, -- used in @ManyToOne
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 🔧 Handover Protocol Table
CREATE TABLE handover_protocols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    comment TEXT,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_device FOREIGN KEY (device_id) REFERENCES devices(id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES departments(id)
);
