--  Department Table
CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100), -- todo unique
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

--  Users Table
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    username VARCHAR(50) NOT NULL UNIQUE, --TODO define contraint for min
    name VARCHAR(100),
    surname VARCHAR(100),
    -- TODO add familyname
    enabled BOOLEAN,
    department_id INTEGER,
    FOREIGN KEY (department_id) REFERENCES departments(id)
);

--  Devices Table
CREATE TABLE devices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    name VARCHAR(100),
    type VARCHAR(50),
    status VARCHAR(50), -- assumes enum is stored as String
    serial_number VARCHAR(50) UNIQUE,
    manufacturer VARCHAR(100),
    location VARCHAR(100),
    purchase_date DATE,
    user_id INTEGER, -- used in @ManyToOne
    FOREIGN KEY (user_id) REFERENCES users(id)
);

--  Handover Protocol Table
CREATE TABLE handover_protocols (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    department_id INTEGER NOT NULL,
    description TEXT,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_device FOREIGN KEY (device_id) REFERENCES devices(id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES departments(id)
);
