-- Department Table
CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Users Table
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    username VARCHAR2(50) NOT NULL UNIQUE,
    name VARCHAR2(100),
    surname VARCHAR2(100),
    familyname VARCHAR2(100),
    enabled NUMBER(1),
    department_id INTEGER,
    CONSTRAINT fk_users_department FOREIGN KEY (department_id) REFERENCES departments(id)
);

-- Devices Table
CREATE TABLE devices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    name VARCHAR2(100),
    type VARCHAR2(50),
    status VARCHAR2(50), -- enum as string
    serial_number VARCHAR2(50) UNIQUE,
    manufacturer VARCHAR2(100),
    location VARCHAR2(100),
    purchase_date DATE,
    user_id INTEGER,
    CONSTRAINT fk_devices_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Handover Protocol Table
CREATE TABLE handover_protocols (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    department_id INTEGER NOT NULL,
    description CLOB,
    confirmed NUMBER(1) DEFAULT 0 NOT NULL,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_handover_device FOREIGN KEY (device_id) REFERENCES devices(id),
    CONSTRAINT fk_handover_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_handover_department FOREIGN KEY (department_id) REFERENCES departments(id)
);
