-- Department Table
CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Users Table
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    username VARCHAR2(50) NOT NULL UNIQUE,
    name VARCHAR2(100),
    surname VARCHAR2(100),
    enabled NUMBER(1),
    department_id INTEGER,
    CONSTRAINT fk_users_department FOREIGN KEY (department_id) REFERENCES departments(id)
);

-- Devices Table
CREATE TABLE devices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    name VARCHAR2(100),
    type VARCHAR2(50),
    status VARCHAR2(50), -- enum as string
    serial_number VARCHAR2(50) UNIQUE,
    manufacturer VARCHAR2(100),
    location VARCHAR2(100),
    purchase_date DATE,
    user_id INTEGER,
    CONSTRAINT fk_devices_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create the HANDOVER_PROTOCOLS table
CREATE TABLE handover_protocols (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
   device_id NUMBER NOT NULL,
   receiver_user_id NUMBER NOT NULL,
   performed_by_user_id NUMBER NOT NULL,
   department_id NUMBER NOT NULL,
   description VARCHAR2(500),
   is_confirmed NUMBER(1) DEFAULT 0,
   confirmed_at TIMESTAMP WITH TIME ZONE,
   created_at TIMESTAMP WITH TIME ZONE,
   updated_at TIMESTAMP WITH TIME ZONE,
   -- you may want this column if you have enum string representation:
   action_type VARCHAR2(50)
);

-- Optionally, add foreign key constraints:
ALTER TABLE handover_protocols ADD CONSTRAINT fk_device
   FOREIGN KEY (device_id)
   REFERENCES devices(id);

ALTER TABLE handover_protocols ADD CONSTRAINT fk_receiver_user
   FOREIGN KEY (receiver_user_id)
   REFERENCES users(id);

ALTER TABLE handover_protocols ADD CONSTRAINT fk_performer_user
   FOREIGN KEY (performed_by_user_id)
   REFERENCES users(id);

ALTER TABLE handover_protocols ADD CONSTRAINT fk_department
   FOREIGN KEY (department_id)
   REFERENCES departments(id);

