-- Department Table
CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE, -- TODO unique
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

-- Users Table
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    username VARCHAR2(50) NOT NULL UNIQUE, -- TODO define constraint for min length
    name VARCHAR2(100),
    surname VARCHAR2(100),
    familyname VARCHAR2(100), -- TODO added familyname
    enabled NUMBER(1), -- BOOLEAN stored as 0 (false) / 1 (true)
    department_id INTEGER,
    CONSTRAINT fk_users_department FOREIGN KEY (department_id) REFERENCES departments(id)
);

-- Devices Table
CREATE TABLE devices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    name VARCHAR2(100),
    type VARCHAR2(50),
    status VARCHAR2(50), -- enum as string
    serial_number VARCHAR2(50) UNIQUE,
    manufacturer VARCHAR2(100),
    location VARCHAR2(100),
    purchase_date DATE,
    user_id INTEGER,
    CONSTRAINT fk_devices_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Handover Protocol Table
CREATE TABLE handover_protocols (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    department_id INTEGER NOT NULL,
    description CLOB,
    confirmed NUMBER(1) DEFAULT 0 NOT NULL, -- BOOLEAN as 0/1
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_handover_device FOREIGN KEY (device_id) REFERENCES devices(id),
    CONSTRAINT fk_handover_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_handover_department FOREIGN KEY (department_id) REFERENCES departments(id)
);
