ALTER SESSION SET CURRENT_SCHEMA = SDMDEV01;
/

-- Departments Table
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE departments (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name VARCHAR2(100) NOT NULL UNIQUE,
       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
       updated_at TIMESTAMP WITH TIME ZONE
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
         NULL; -- Table already exists
      ELSE
         RAISE;
      END IF;
END;
/

-- Users Table
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE users (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
       updated_at TIMESTAMP WITH TIME ZONE,
       username VARCHAR2(50) NOT NULL UNIQUE,
       name VARCHAR2(100),
       surname VARCHAR2(100),
       enabled NUMBER(1),
       department_id INTEGER,
       CONSTRAINT fk_users_department FOREIGN KEY (department_id) REFERENCES departments(id)
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
         NULL;
      ELSE
         RAISE;
      END IF;
END;
/

-- Devices Table
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE devices (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
       updated_at TIMESTAMP WITH TIME ZONE,
       name VARCHAR2(100),
       type VARCHAR2(50),
       status VARCHAR2(50),
       serial_number VARCHAR2(50) UNIQUE,
       manufacturer VARCHAR2(100),
       location VARCHAR2(100),
       purchase_date DATE,
       user_id INTEGER,
       CONSTRAINT fk_devices_user FOREIGN KEY (user_id) REFERENCES users(id)
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
         NULL;
      ELSE
         RAISE;
      END IF;
END;
/

-- Handover Protocols Table
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE handover_protocols (
       id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
       device_id NUMBER NOT NULL,
       receiver_user_id NUMBER NOT NULL,
       performed_by_user_id NUMBER NOT NULL,
       department_id NUMBER NOT NULL,
       description VARCHAR2(500),
       is_confirmed NUMBER(1) DEFAULT 0,
       confirmed_at TIMESTAMP WITH TIME ZONE,
       created_at TIMESTAMP WITH TIME ZONE,
       updated_at TIMESTAMP WITH TIME ZONE,
       action_type VARCHAR2(50),
       handover_date TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
         NULL;
      ELSE
         RAISE;
      END IF;
END;
/

-- Add foreign key constraints to handover_protocols (if not already present via table creation)
-- Since they were missing from the initial CREATE statement and added via ALTER, 
-- we wrap them in PL/SQL as well to avoid errors if they already exist.
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE handover_protocols ADD CONSTRAINT fk_device FOREIGN KEY (device_id) REFERENCES devices(id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -2275 OR SQLCODE = -2260 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE handover_protocols ADD CONSTRAINT fk_receiver_user FOREIGN KEY (receiver_user_id) REFERENCES users(id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -2275 OR SQLCODE = -2260 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE handover_protocols ADD CONSTRAINT fk_performer_user FOREIGN KEY (performed_by_user_id) REFERENCES users(id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -2275 OR SQLCODE = -2260 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE handover_protocols ADD CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES departments(id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -2275 OR SQLCODE = -2260 THEN NULL; ELSE RAISE; END IF;
END;
/

